---
- name: Resize VM Memory
  hosts: localhost # if you have inventory add the group name where you want to increase memory
  gather_facts: no
  pre_tasks:
  - include_vars: vars.yml
  vars:
    memory_mb: "{{ memory_mb }}"  # Specify the desired CPU count here

  tasks:
    - name: Resize VM CPU
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no  
        name: "{{ vm_name }}"
        state: present  
        hardware:
          memory_mb: "{{ memory_mb }}"
          hotadd_memory: true
